### ISSUE TITLE
bug for make

### ISSUE THREAD

**Issue by x5engine** [oohnoitz/nginx-installer#3]
Hi there,

I got this error when I try to install nginx

```
Configuring... --with-debug --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module
./configure: error: invalid option "--with-http_v2_module"
Compiling...
make: *** No targets specified and no makefile found.  Stop.
Installing...
make: *** No rule to make target 'install'.  Stop.
Finished!
```

Thanks for this tool!

**Comment by oohnoitz** [comment]
What version of nginx are you trying to install? `--with-http_v2_module` should be a valid config flag for v1.9.5+.

https://nginx.org/en/docs/http/ngx_http_v2_module.html

**Comment by erinfotech** [comment]
root@test:~/nginx-installer# sudo ./install-nginx.sh 1.5.10
Downloading: nginx-1.5.10 ...   [DONE]
Extracting:  nginx-1.5.10 ...   [DONE]
Configuring... --with-debug --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module
./configure: error: invalid option "--with-http_v2_module"
Compiling...
make: *** No targets specified and no makefile found.  Stop.
Installing...
make: *** No rule to make target 'install'.  Stop.
Finished!

**Comment by erinfotech** [comment]
sudo ./install-nginx.sh 1.5.10
Downloading: nginx-1.5.10 ... [DONE]
Extracting: nginx-1.5.10 ... [DONE]
Configuring... --with-debug --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module
./configure: error: invalid option "--with-http_v2_module"
Compiling...
make: *** No targets specified and no makefile found. Stop.
Installing...
make: *** No rule to make target 'install'. Stop.
Finished!

**Comment by erinfotech** [comment]
even If we tried to install the 1.5.10 (old) version also getting the same error.

**Comment by oohnoitz** [comment]
@erinfotech That seems accurate. `--with-http_v2_module` is something that requires 1.9.5+. It should break for 1.5.x since the spdy module was used around then.

I've typically updated the `CONFIGURE_PARAMS` based on latest stable some some of preferred defaults. However, you should be able to remove it from https://github.com/oohnoitz/nginx-installer/blob/master/install-nginx.sh#L3 manually if you still need to run on anything older than 1.9.x.

**Comment by oohnoitz** [comment]
Going to close this since `stable` and `mainline` versions is what I've been targeting with this project.
