### ISSUE TITLE
How to make with module and install

### ISSUE THREAD

**Issue by padma-lakshmi** [oohnoitz/nginx-installer#4]
Hi, want to install ngx_rtmp, can you please give me the commands.
I tried several times but getting error.

sudo apt update
adduser testuser
usermod -aG sudo testuser

apt-get update
apt-get install git-core

cd testuser
git clone https://github.com/oohnoitz/nginx-installer.git

after that I'm unable to include the modules

./install-module.sh <ngx_rtmp>` 
./install-module.sh ngx_rtmp
./install-module.sh arut

tried above 3 commands but not working.

**Comment by padma-lakshmi** [comment]
can you please send me the commands

**Comment by padma-lakshmi** [comment]
![image](https://user-images.githubusercontent.com/58339401/84941436-0bd6d880-b0ff-11ea-95ef-ec765ca8ad1d.png)

**Comment by oohnoitz** [comment]
`./install-module.sh ngx_rtmp` is the correct command, but would be helpful to have the error message to see what went wrong.

It should show something like the following when you run the command:

```
❯ ./install-module.sh ngx_rtmp
Downloading: ngx_rtmp ...
Cloning into 'modules/ngx_rtmp'...
remote: Enumerating objects: 4314, done.
remote: Total 4314 (delta 0), reused 0 (delta 0), pack-reused 4314
Receiving objects: 100% (4314/4314), 3.10 MiB | 17.63 MiB/s, done.
Resolving deltas: 100% (2686/2686), done.
```

**Comment by padma-lakshmi** [comment]
tester@Test:~$ ./install-module.sh ngx_rtmp
bash: ./install-module.sh: No such file or directory

**Comment by erinfotech** [comment]
sorry, not entered into directory.

**Comment by padma-lakshmi** [comment]
Thank you so much, issue resolved.

**Comment by padma-lakshmi** [comment]
tester@Test:~/nginx-installer$ sudo ./install-nginx.sh 1.18.0
Downloading: nginx-1.18.0 ...   [DONE]
Extracting:  nginx-1.18.0 ...   [DONE]
Applying Patch: *
./install-nginx.sh: line 58: patches/*: No such file or directory
Configuring... --with-debug --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --add-module=modules/ngx_rtmp
checking for OS
 + Linux 4.15.0-101-generic x86_64
checking for C compiler ... not found

./configure: error: C compiler cc is not found

Compiling...
make: *** No rule to make target 'build', needed by 'default'.  Stop.
Installing...
make: *** No rule to make target 'install'.  Stop.
Finished!
tester@Test:~/nginx-installer$

installation is not successful.
